language: ruby
cache: bundler

rvm:
  - 2.1.0

branches:
  only:
    - refactor

<<<<<<< HEAD
script: "bundle exec rspec"

=======
>>>>>>> master
notifications:
  email:
    recipients:
      - mamuso@mamuso.net
    on_failure: change
    on_success: never