language: ruby
cache: bundler

rvm:
  - 2.1.0

branches:
  only:
    - master
    - refactor

script: "bundle exec rspec"

notifications:
  email:
    recipients:
      - mamuso@mamuso.net
    on_failure: change
    on_success: never